apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kafka-to-influxdb-latest
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kafka-to-influxdb-latest
    app.kubernetes.io/part-of: kafka-to-influxdb-1
  name: kafka-to-influxdb-latest
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kafka-to-influxdb-latest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kafka-to-influxdb-latest
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rshah-tenant/kafka-to-influxdb-1/kafka-to-influxdb-latest@sha256:a975836cefdb59c205243a514f6154276c389b943924e4245c89a2f70ef4dfb8
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
