apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kafka-to-influxdb-latest
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kafka-to-influxdb-latest
    app.kubernetes.io/part-of: kafka-to-influxdb-1
  name: kafka-to-influxdb-latest
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: kafka-to-influxdb-latest
status:
  loadBalancer: {}
